# Generated by Django 5.1.7 on 2025-03-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(default='White', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='flavor_text',
            field=models.CharField(default='Hello World', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(default='3B', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='rules_text',
            field=models.CharField(default='Hello World', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='stats',
            field=models.CharField(default=1.0, max_length=10),
            preserve_default=False,
        ),
    ]
