# Generated by Django 5.1.7 on 2025-03-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_card_id_alter_card_card_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtyperel',
            name='card_type',
            field=models.CharField(choices=[('CREATURE', 'Creature'), ('SORCERY', 'Sorcery'), ('INSTANT', 'Instant'), ('ENCHANTMENT', 'Enchantment'), ('ARTIFACT', 'Artifact'), ('PLANESWALKER', 'Planeswalker'), ('BATTLE', 'Battle'), ('LAND', 'Land')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supertyperel',
            name='super_type',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('LEGENDARY', 'Legendary'), ('SNOW', 'Snow'), ('WORLD', 'World')], default='LEGENDARY', max_length=12),
        ),
        migrations.AlterField(
            model_name='subtyperel',
            name='sub_type',
            field=models.CharField(max_length=30),
        ),
    ]
