# Generated by Django 5.1.7 on 2025-05-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardtyperel_card_type_supertyperel_super_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtyperel',
            name='card_type',
            field=models.CharField(choices=[('CREATURE', 'Creature'), ('SORCERY', 'Sorcery'), ('INSTANT', 'Instant'), ('ENCHANTMENT', 'Enchantment'), ('ARTIFACT', 'Artifact'), ('PLANESWALKER', 'Planeswalker'), ('BATTLE', 'Battle'), ('LAND', 'Land')], db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='supertyperel',
            name='super_type',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('LEGENDARY', 'Legendary'), ('SNOW', 'Snow'), ('WORLD', 'World')], db_index=True, default='LEGENDARY', max_length=12),
        ),
    ]
