# Generated by Django 5.1.7 on 2025-05-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cardtyperel_card_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
